In [1]:
import pandas as pd

In [45]:
dd = pd.read_csv("./datasets/daraz_dataset.csv")
dd.shape
# print(dd.head(13))
# print(dd.head(1))
# print(dd.shape)
# print(dd.columns)
# print(dd.info())
# print(dd["TotalAmount"].max())
# print(dd["TotalAmount"].min())
# print(dd["TotalAmount"].mean())
# print(dd[["CustomerName","District","TotalAmount"]])
# print(dd.iloc[11]) 11 index ko rows lai tanyo 
# print(dd.iloc[0:5])
# print(dd.iloc[0,2]) specific cell lai capture garna sakinxa
# print(dd.iloc[:,[2,6,8]])
# print(dd.iloc[-1])
# print(dd.iloc[0:5,0:3])
# print(dd.loc[:,["District","CustomerName"]])
# print(dd.loc[dd["District"]=="Kathmandu"])
# print(dd.loc[dd["TotalAmount"]>30000])
#filter chaining --> kathmandu district, esewa paymentMethod
# print(dd.loc[(dd["District"]=="Kathmandu") & (dd["PaymentMethod"]=="eSewa")])
#category="Electronics" & Rating=5

# print(dd.sort_values("TotalAmount",ascending=False))

(500, 15)

In [46]:
bdd = pd.read_csv("datasets/bad_daraz_dataset (1).csv")
bdd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,abc,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,10,Keyboard,Electronics,2500,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
10,11,Bottle,Home,800,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
11,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44
12,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [27]:
# bdd.isnull().sum() nan, missing values datatypes catch and sum
# bdd.fillna(0) missing values ma 0 haldinxa
bdd["price"]=pd.to_numeric(bdd["price"],errors="coerce")
bdd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500.0,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500.0,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500.0,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200.0,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,NaN,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800.0,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,10,Keyboard,Electronics,2500.0,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
10,11,Bottle,Home,800.0,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
11,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [31]:
bdd["price"]=bdd["price"].fillna(bdd["price"].mean())
bdd
# dummy = pd.Series(["100","200","abc"])
# pd.to_numeric(dummy,errors="coerce")

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,16730.0,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500.0,5%,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500.0,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500.0,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200.0,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,16730.0,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800.0,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,10,Keyboard,Electronics,2500.0,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
10,11,Bottle,Home,800.0,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
11,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44

In [38]:
bdd["age"]= pd.to_numeric(bdd["age"],errors="coerce")
bdd["age"] = bdd["age"].fillna(bdd["age"].median())
bdd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
1,2,Phone,Electronics,16730.0,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30.0,210
2,3,Shoes,Fashion,3500.0,5%,4.2,60,FashionHub,Itahari,Nike,Male,22.0,55
3,4,T-Shirt,Fashion,1500.0,20,NaN,150,Style,Biratnagar,Adidas,Female,25.0,30
4,5,Watch,Accessories,5500.0,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28.0,80
5,6,Headphones,Electronics,4200.0,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24.0,65
6,7,Laptop,Electronics,75000.0,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25.0,120
7,8,Bag,Fashion,16730.0,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19.0,18
8,9,Mouse,Electronics,1800.0,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,25.0,90
9,10,Keyboard,Electronics,2500.0,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21.0,110
10,11,Bottle,Home,800.0,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26.0,12
11,12,Chair,Furniture,-2500.0,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,25.0,44

In [56]:
# bdd.dropna()\
# bdd[bdd.duplicated()]
bdd["discount_percent"] =bdd["discount_percent"].str.replace("%","")
bdd

,product_id,product_name,category,price,discount_percent,rating,stock,seller,city,brand,gender_target,age,reviews
0,1,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
1,2,Phone,Electronics,NaN,15,4.6,40,GadgetNepal,Pokhara,Samsung,Unisex,30,210
2,3,Shoes,Fashion,3500,5,4.2,60,FashionHub,Itahari,Nike,Male,22,55
3,4,T-Shirt,Fashion,1500,20,NaN,150,Style,Biratnagar,Adidas,Female,Female,30
4,5,Watch,Accessories,5500,10,4.5,Out of Stock,TimeX,Kathmandu,Casio,Male,28,80
5,6,Headphones,Electronics,4200,NaN,4.1,75,AudioPro,Pokhara,JBL,Unisex,24,65
6,7,Laptop,Electronics,75000,10,4.8,25,TechHub,Kathmandu,Dell,Unisex,25,120
7,8,Bag,Fashion,abc,12,3.9,45,CarryAll,Dharan,Wildcraft,Female,19,18
8,9,Mouse,Electronics,1800,5,4.3,NaN,TechHub,Kathmandu,Logitech,Unisex,NaN,90
9,10,Keyboard,Electronics,2500,5,4.4,35,TechHub,Kathmandu,Logitech,Unisex,21,110
10,11,Bottle,Home,800,0,5.5,100,HomeStore,Janakpur,Generic,Unisex,26,12
11,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44
12,12,Chair,Furniture,-2500,10,4.0,-5,FurniCo,Lalitpur,IKEA,Unisex,Unknown,44